name: Run Protractor Tests on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Download ChromeDriver
      run: |
        npm install -g chromedriver

    - name: Install Selenium WebDriver
      run: |
        npm install -g webdriver-manager
        webdriver-manager update

    - name: Start Selenium WebDriver
      run: |
        npx webdriver-manager start &
      shell: cmd

    - name: Run Protractor Tests
      run: |
        npx protractor protractor.conf.js
      shell: cmd
