name: Run Protractor Tests

on:
  push:
    branches:
      - main  # Adjust according to your branch name
  pull_request:
    branches:
      - main  # Adjust according to your branch name

jobs:
  protractor_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Update WebDriver Manager
        run: |
          echo "Updating WebDriver Manager..."
          npx webdriver-manager update

      - name: Start WebDriver Manager
        run: |
          echo "Starting WebDriver Manager..."
          npx webdriver-manager start &
          sleep 5
          curl http://localhost:4444/wd/hub/status

      - name: Serve Angular Project
        run: |
          echo "Serving Angular project..."
          npm run start &
        env:
          NG_CLI_ANALYTICS: "false"  # Disable analytics prompts for ng CLI

      - name: Wait for Angular to Start
        run: |
          echo "Waiting for Angular app to start..."
          for i in {1..30}; do
            if curl -s -o /dev/null -w "%{http_code}" http://localhost:4200 | grep -q "200"; then
              echo "Angular app is up!"
              break
            fi
            echo "Waiting for Angular app to start ($i/30)..."
            sleep 5
          done
          if ! curl -s -o /dev/null -w "%{http_code}" http://localhost:4200 | grep -q "200"; then
            echo "Angular app did not start in time"
            exit 1
          fi

      - name: Run Protractor Tests
        run: |
          echo "Running Protractor tests..."
          npx protractor protractor.conf.js
