name: Protractor Tests

on:
  push:

jobs:
  protractor_tests:
    # runs-on: self-hosted
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Setup Node.js
        # uses: actions/setup-node@v2
        # with:
        #   node-version: '20'

      # - name: Start WebDriver and run Protractor tests
      #   run: |
         
      #     bash run_protractor_tests.sh start

      # - name: Stop WebDriver
      #   run: bash run_protractor_tests.sh stop
          
      - name: Run protractor testcaes 
        run: npx protractor "C:\Users\sandhata\shirisha dodla\UI_testing_nextgen\Nextgen_test\protractor.conf.js"
