name: Protractor Tests

on: [push]

jobs:
  protractor_tests:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # - name: Install Dependencies
      #   run: |
      #     echo "Installing project dependencies..."
      #     npm install
      #     echo "Installing Protractor globally..."
      #     npm install -g protractor

      # - name: Set npm global directory
      #   run: |
      #     echo "Configuring npm global directory..."
      #     npm config set prefix "C:\Users\runneradmin\AppData\Roaming\npm"
      #   shell: powershell

      # - name: Ensure npm global bin directory is in PATH
      #   run: |
      #     echo "Adding npm global bin directory to PATH..."
      #     $env:Path += ";C:\Users\runneradmin\AppData\Roaming\npm"
      #   shell: powershell

      - name: Run Protractor Tests
        run: |
          echo "Running Protractor tests..."
          npx protractor "C:\Users\sandhata\shirisha dodla\UI_testing_nextgen\Nextgen_test\protractor.conf.js"
        shell: powershell
