name: Protractor Tests

on:
  push:

jobs:
  protractor_tests:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start WebDriver
        run: bash C:\Users\sandhata\Desktop\test.sh start

      # - name: Run Protractor Tests
      #   run: npx protractor "C:/Users/sandhata/shirisha dodla/UI_testing_nextgen/Nextgen_test/protractor.conf.js"

      - name: Stop WebDriver
        # if: always()
        run: C:\Users\sandhata\Desktop\test.sh stop
