name: Protractor Tests

on: [push]

jobs:
  protractor_tests:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Protractor Tests
        run: |
          echo "Running Protractor tests..."
          protractor protractor.conf.js
