name: startservices

on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: [self-hosted, Windows]

    env:
      PATH: 'C:\\Program Files\\Git\\bin;C:\\Program Files\\nodejs;C:\\Windows\\System32;C:\\Users\\sandhata\\AppData\\Roaming\\npm;C:\\Program Files\\Java\\jdk1.8.0_321\\bin'

    steps:
      - name: Check versions
        shell: bash
        run: |
          echo "PATH is: $PATH"
          echo "Checking Git version..."
          git --version
          echo "Checking Node.js version..."
          node --version
          echo "Checking npm version..."
          npm --version
          echo "Checking Java version..."
          java -version

      - name: Run Bash script
        shell: bash
        run: bash /c/Users/sandhata/Downloads/startcardservices.sh
