name: startservices

on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Check versions
        shell: pwsh
        run: |
          Write-Host "Initial PATH is: $env:PATH"
          Write-Host "Checking Git version..."
          git --version
          Write-Host "Checking Node.js version..."
          node --version
          Write-Host "Checking npm version..."
          npm --version
          Write-Host "Checking Java version..."
          java -version

      - name: Run Bash script
        shell: pwsh
        run: |
          bash /c/Users/sandhata/Downloads/startcardservices.sh
