name: startservices

on:
  workflow_dispatch:

jobs:
  startservices:
    runs-on: [self-hosted, windows]
    env:
      PATH: C:\Program Files\Git\bin;C:\Program Files\nodejs;C:\Windows\System32;C:\Users\sandhata\AppData\Roaming\npm;C:\Program Files\Java\jdk1.8.0_321\bin

    steps:
      - name: Clean Up Repository Directory
        shell: cmd
        run: |
          rmdir /S /Q C:\Windows\actions-runner\test-runner\_work\Nextgen_test\Nextgen_test
        
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Git for Windows
        shell: cmd
        run: |
          "C:\Program Files\Git\bin\bash.exe" --version
      
      - name: Start WebDriver
        shell: cmd
        run: |
          "C:\Program Files\Git\bin\bash.exe" C:\Users\sandhata\Downloads\startcardservices.sh
