name: Run Protractor Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Download and update ChromeDriver
      run: npx webdriver-manager update --versions.chrome $(npx chromedriver --version | grep -oP '\d+\.\d+\.\d+')

    - name: Start Selenium server
      run: Start-Process 'npx' -ArgumentList 'webdriver-manager start' -NoNewWindow; Start-Sleep -Seconds 10
      shell: pwsh

    # - name: Wait for Selenium server
    #   run: |
    #     $url = 'http://localhost:4444/wd/hub'
    #     $maximumWaitTimeInSeconds = 60
    #     $start = Get-Date
    #     $webRequest = $null

    #     do {
    #       try {
    #         $webRequest = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 1
    #         if ($webRequest.StatusCode -eq 200) {
    #           Write-Host "Selenium server is ready!"
    #           exit 0
    #         }
    #       }
    #       catch {
    #         # Do nothing, just continue waiting
    #       }
    #       Start-Sleep -Seconds 1
    #     }
    #     while ((New-TimeSpan -Start $start).TotalSeconds -lt $maximumWaitTimeInSeconds)

    #     Write-Host "Selenium server did not start within the maximum wait time."
    #     exit 1
    #   shell: pwsh

    - name: Run Protractor tests
      run: npx protractor protractor.conf.js
