name: Run Protractor Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Download and update ChromeDriver
      run: |
        $chromeVersion = (npx chromedriver --version) -match '\d+\.\d+\.\d+'
        if ($matches[0]) {
          npx webdriver-manager update --versions.chrome $matches[0]
        } else {
          Write-Error "Failed to determine ChromeDriver version"
        }
      shell: pwsh

    - name: Start Selenium server in the background
      run: |
        Start-Process -FilePath "npx" -ArgumentList "webdriver-manager start" -PassThru -NoNewWindow
      shell: pwsh

    - name: Wait for Selenium server to start
      run: |
        $maxAttempts = 5
        $attempt = 0
        while ($attempt -lt $maxAttempts) {
          $response = Invoke-WebRequest -Uri http://localhost:4444/ -UseBasicParsing
          if ($response.StatusCode -eq 200) {
            Write-Host "Selenium Server is up and running."
            break
          }
          else {
            Write-Host "Waiting for Selenium Server to start..."
            Start-Sleep -Seconds 10
            $attempt++
          }
        }
        if ($attempt -eq $maxAttempts) {
          throw "Selenium Server did not start in time."
        }
      shell: pwsh

    - name: Run Protractor tests
      run: npx protractor protractor.conf.js
